version: '3'

networks:
  app-network:
    driver: bridge

volumes:
  mysql:
    driver: local

services:
# Application ############################################
  app:
    build: .
    container_name: app
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - app-network

# NGINX Server ############################################
  nginx:
    build:
      context: .docker/nginx
    container_name: nginx
    restart: always
    tty: true
    volumes:
      - .:/var/www
    ports:
      - "8000:80"
    networks:
      - app-network

# Database ###################################################
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

# Redis #################################################
  redis:
    image: redis:alpine
    container_name: redis
    expose:
      - 6379
    networks:
      - app-network
